// portfolio/components/Dot.svelte
<script>
  export let project = ''
  let colors = {
    compromise: '#6699cc',
    wikipedia: '#50617A',
    freebase: '#6accb2',
    simple: '#e6b3bc'
  }
  let color = colors[project] || 'steelblue'
</script>

<style>
  .dot {
    margin-right: 15px;
    margin-top: 20px;
    height: 15px;
    width: 15px;
    border-radius: 20%;
    display: inline-block;
  }
</style>

<div class="dot" style="background-color:{color};" />

// pages/portfolio/Dot.vue
<script setup>
import colors from '~/assets/colors.js'

// small coloured square marking which project a citation is about
const props = defineProps({ project: { type: String, default: '' } })
const projects = { compromise: colors.blue, wikipedia: colors.sea, freebase: colors.green, simple: '#e6b3bc' }
const color = computed(() => projects[props.project] || 'steelblue')
</script>

<template>
  <div class="mt-5 mr-[15px] inline-block h-[15px] w-[15px] rounded-[20%]" :style="{ backgroundColor: color }" />
</template>
